'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SelfCon.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property accept_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("accept_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property alarm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alarm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property autoload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("autoload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property autoloadbg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("autoloadbg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btautoc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btautoc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btautol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btautol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btChangeUser2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btChangeUser2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btn3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property checked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("checked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cleanselfcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cleanselfcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property config() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("config", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property connected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("connected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property couldnotfindwsfromdb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("couldnotfindwsfromdb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property discon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("discon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dos1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dos1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property error_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("error_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property errorwhilegettingdata() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("errorwhilegettingdata", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FTShokoNotFinished() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FTShokoNotFinished", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icon_erase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_erase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property input_blank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("input_blank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property input_error_messages5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("input_error_messages5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property input_error_messages7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("input_error_messages7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property input_successed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("input_successed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property inputbg2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inputbg2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Maintenance1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Maintenance1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Maintenance2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Maintenance2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mode_m() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mode_m", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property noimage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("noimage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property NumericOnly() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NumericOnly", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property planStop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("planStop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property QrScanner64() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("QrScanner64", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ROHM25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ROHM25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property setup_result_header() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("setup_result_header", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SetupEquipment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SetupEquipment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property smallQr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("smallQr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stop_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stop_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property unknowformat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unknowformat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property warn_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("warn_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property WorkRecord() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WorkRecord", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
