'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.0.102;Initial Catalog=DBx;Persist Security Info=True;User ID=d"& _ 
            "bxuser")>  _
        Public ReadOnly Property DBxConnectionString() As String
            Get
                Return CType(Me("DBxConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://webserv.thematrix.net:7777/EmsService")>  _
        Public Property EmsServiceUrl() As String
            Get
                Return CType(Me("EmsServiceUrl"),String)
            End Get
            Set
                Me("EmsServiceUrl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("FT")>  _
        Public Property ProcessName() As String
            Get
                Return CType(Me("ProcessName"),String)
            End Get
            Set
                Me("ProcessName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("99")>  _
        Public Property LineNo() As String
            Get
                Return CType(Me("LineNo"),String)
            End Get
            Set
                Me("LineNo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://webserv.thematrix.net/LsiPETE/LSI_Prog/Maintenance/MainloginPD.asp")>  _
        Public Property BMRequestUrl() As String
            Get
                Return CType(Me("BMRequestUrl"),String)
            End Get
            Set
                Me("BMRequestUrl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://webserv.thematrix.net/LsiPETE/LSI_Prog/Maintenance/MainPMlogin.asp")>  _
        Public Property PMRequestUrl() As String
            Get
                Return CType(Me("PMRequestUrl"),String)
            End Get
            Set
                Me("PMRequestUrl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://webserv.thematrix.net/andon")>  _
        Public Property AndonRequestUrl() As String
            Get
                Return CType(Me("AndonRequestUrl"),String)
            End Get
            Set
                Me("AndonRequestUrl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Program Files\Internet Explorer\iexplore.exe")>  _
        Public Property InternetExplorerProgramFileName() As String
            Get
                Return CType(Me("InternetExplorerProgramFileName"),String)
            End Get
            Set
                Me("InternetExplorerProgramFileName") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=10.28.1.144;Initial Catalog=DBLSISHT;Persist Security Info=True;User "& _ 
            "ID=ship;Password=ship")>  _
        Public ReadOnly Property DBLSISHTConnectionString() As String
            Get
                Return CType(Me("DBLSISHTConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("600000")>  _
        Public Property SaveStateInterval() As Integer
            Get
                Return CType(Me("SaveStateInterval"),Integer)
            End Get
            Set
                Me("SaveStateInterval") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7")>  _
        Public Property ClearLogIntervalDays() As Integer
            Get
                Return CType(Me("ClearLogIntervalDays"),Integer)
            End Get
            Set
                Me("ClearLogIntervalDays") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2013-11-13")>  _
        Public Property ClearLogTimeStamp() As Date
            Get
                Return CType(Me("ClearLogTimeStamp"),Date)
            End Get
            Set
                Me("ClearLogTimeStamp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("FT-GL")>  _
        Public Property GroupLeaderGroupName() As String
            Get
                Return CType(Me("GroupLeaderGroupName"),String)
            End Get
            Set
                Me("GroupLeaderGroupName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("AUTOMOTIVE")>  _
        Public Property AutomotiveGroupName() As String
            Get
                Return CType(Me("AutomotiveGroupName"),String)
            End Get
            Set
                Me("AutomotiveGroupName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("FT-SETUP")>  _
        Public Property SetupGroupName() As String
            Get
                Return CType(Me("SetupGroupName"),String)
            End Get
            Set
                Me("SetupGroupName") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.0.102;Initial Catalog=DBx;Persist Security Info=True;User ID=b"& _ 
            "omuser;Password=bomu$er")>  _
        Public ReadOnly Property BomConnectionString() As String
            Get
                Return CType(Me("BomConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property TdcEnabled() As Boolean
            Get
                Return CType(Me("TdcEnabled"),Boolean)
            End Get
            Set
                Me("TdcEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property EmsEnabled() As Boolean
            Get
                Return CType(Me("EmsEnabled"),Boolean)
            End Get
            Set
                Me("EmsEnabled") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://webserv.thematrix.net/bom/Default.aspx")>  _
        Public Property BomWebsiteUrl() As String
            Get
                Return CType(Me("BomWebsiteUrl"),String)
            End Get
            Set
                Me("BomWebsiteUrl") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ShowFTPanelGrid() As Boolean
            Get
                Return CType(Me("ShowFTPanelGrid"),Boolean)
            End Get
            Set
                Me("ShowFTPanelGrid") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9")>  _
        Public Property FTProcessID() As Integer
            Get
                Return CType(Me("FTProcessID"),Integer)
            End Get
            Set
                Me("FTProcessID") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=172.16.0.102;Initial Catalog=APCSDB;Persist Security Info=True;User I"& _ 
            "D=apcsdbuser")>  _
        Public ReadOnly Property TDCConnectionString() As String
            Get
                Return CType(Me("TDCConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("06:00:00")>  _
        Public Property EcoWatchDuration() As Global.System.TimeSpan
            Get
                Return CType(Me("EcoWatchDuration"),Global.System.TimeSpan)
            End Get
            Set
                Me("EcoWatchDuration") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("FT-OP")>  _
        Public Property FTOPGroupName() As String
            Get
                Return CType(Me("FTOPGroupName"),String)
            End Get
            Set
                Me("FTOPGroupName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Log")>  _
        Public Property LogDirectory() As String
            Get
                Return CType(Me("LogDirectory"),String)
            End Get
            Set
                Me("LogDirectory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DataError")>  _
        Public Property DataErrorDirectory() As String
            Get
                Return CType(Me("DataErrorDirectory"),String)
            End Get
            Set
                Me("DataErrorDirectory") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("State")>  _
        Public Property StateDirectory() As String
            Get
                Return CType(Me("StateDirectory"),String)
            End Get
            Set
                Me("StateDirectory") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SelfCon.My.MySettings
            Get
                Return Global.SelfCon.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
