'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Rohm.FT.SettingService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Rohm.FT.SettingService.SettingServiceSoap")>  _
    Public Interface SettingServiceSoap
        
        'CODEGEN: Generating message contract since element name testerType from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetMailBoxPath", ReplyAction:="*")>  _
        Function GetMailBoxPath(ByVal request As Rohm.FT.SettingService.GetMailBoxPathRequest) As Rohm.FT.SettingService.GetMailBoxPathResponse
        
        'CODEGEN: Generating message contract since element name flowName from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTestFlowNo", ReplyAction:="*")>  _
        Function GetTestFlowNo(ByVal request As Rohm.FT.SettingService.GetTestFlowNoRequest) As Rohm.FT.SettingService.GetTestFlowNoResponse
        
        'CODEGEN: Generating message contract since element name errorNo from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LotRptIsIgnore", ReplyAction:="*")>  _
        Function LotRptIsIgnore(ByVal request As Rohm.FT.SettingService.LotRptIsIgnoreRequest) As Rohm.FT.SettingService.LotRptIsIgnoreResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetMailBoxPathRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetMailBoxPath", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Rohm.FT.SettingService.GetMailBoxPathRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Rohm.FT.SettingService.GetMailBoxPathRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetMailBoxPathRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public testerType As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal testerType As String)
            MyBase.New
            Me.testerType = testerType
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetMailBoxPathResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetMailBoxPathResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Rohm.FT.SettingService.GetMailBoxPathResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Rohm.FT.SettingService.GetMailBoxPathResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetMailBoxPathResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetMailBoxPathResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetMailBoxPathResult As String)
            MyBase.New
            Me.GetMailBoxPathResult = GetMailBoxPathResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetTestFlowNoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetTestFlowNo", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Rohm.FT.SettingService.GetTestFlowNoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Rohm.FT.SettingService.GetTestFlowNoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetTestFlowNoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public flowName As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal flowName As String)
            MyBase.New
            Me.flowName = flowName
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetTestFlowNoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetTestFlowNoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Rohm.FT.SettingService.GetTestFlowNoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Rohm.FT.SettingService.GetTestFlowNoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetTestFlowNoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetTestFlowNoResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetTestFlowNoResult As String)
            MyBase.New
            Me.GetTestFlowNoResult = GetTestFlowNoResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LotRptIsIgnoreRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LotRptIsIgnore", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Rohm.FT.SettingService.LotRptIsIgnoreRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Rohm.FT.SettingService.LotRptIsIgnoreRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class LotRptIsIgnoreRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public errorNo As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal errorNo As String)
            MyBase.New
            Me.errorNo = errorNo
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LotRptIsIgnoreResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LotRptIsIgnoreResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Rohm.FT.SettingService.LotRptIsIgnoreResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Rohm.FT.SettingService.LotRptIsIgnoreResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class LotRptIsIgnoreResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public LotRptIsIgnoreResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LotRptIsIgnoreResult As Boolean)
            MyBase.New
            Me.LotRptIsIgnoreResult = LotRptIsIgnoreResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface SettingServiceSoapChannel
        Inherits Rohm.FT.SettingService.SettingServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class SettingServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of Rohm.FT.SettingService.SettingServiceSoap)
        Implements Rohm.FT.SettingService.SettingServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Rohm_FT_SettingService_SettingServiceSoap_GetMailBoxPath(ByVal request As Rohm.FT.SettingService.GetMailBoxPathRequest) As Rohm.FT.SettingService.GetMailBoxPathResponse Implements Rohm.FT.SettingService.SettingServiceSoap.GetMailBoxPath
            Return MyBase.Channel.GetMailBoxPath(request)
        End Function
        
        Public Function GetMailBoxPath(ByVal testerType As String) As String
            Dim inValue As Rohm.FT.SettingService.GetMailBoxPathRequest = New Rohm.FT.SettingService.GetMailBoxPathRequest
            inValue.Body = New Rohm.FT.SettingService.GetMailBoxPathRequestBody
            inValue.Body.testerType = testerType
            Dim retVal As Rohm.FT.SettingService.GetMailBoxPathResponse = CType(Me,Rohm.FT.SettingService.SettingServiceSoap).GetMailBoxPath(inValue)
            Return retVal.Body.GetMailBoxPathResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Rohm_FT_SettingService_SettingServiceSoap_GetTestFlowNo(ByVal request As Rohm.FT.SettingService.GetTestFlowNoRequest) As Rohm.FT.SettingService.GetTestFlowNoResponse Implements Rohm.FT.SettingService.SettingServiceSoap.GetTestFlowNo
            Return MyBase.Channel.GetTestFlowNo(request)
        End Function
        
        Public Function GetTestFlowNo(ByVal flowName As String) As String
            Dim inValue As Rohm.FT.SettingService.GetTestFlowNoRequest = New Rohm.FT.SettingService.GetTestFlowNoRequest
            inValue.Body = New Rohm.FT.SettingService.GetTestFlowNoRequestBody
            inValue.Body.flowName = flowName
            Dim retVal As Rohm.FT.SettingService.GetTestFlowNoResponse = CType(Me,Rohm.FT.SettingService.SettingServiceSoap).GetTestFlowNo(inValue)
            Return retVal.Body.GetTestFlowNoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Rohm_FT_SettingService_SettingServiceSoap_LotRptIsIgnore(ByVal request As Rohm.FT.SettingService.LotRptIsIgnoreRequest) As Rohm.FT.SettingService.LotRptIsIgnoreResponse Implements Rohm.FT.SettingService.SettingServiceSoap.LotRptIsIgnore
            Return MyBase.Channel.LotRptIsIgnore(request)
        End Function
        
        Public Function LotRptIsIgnore(ByVal errorNo As String) As Boolean
            Dim inValue As Rohm.FT.SettingService.LotRptIsIgnoreRequest = New Rohm.FT.SettingService.LotRptIsIgnoreRequest
            inValue.Body = New Rohm.FT.SettingService.LotRptIsIgnoreRequestBody
            inValue.Body.errorNo = errorNo
            Dim retVal As Rohm.FT.SettingService.LotRptIsIgnoreResponse = CType(Me,Rohm.FT.SettingService.SettingServiceSoap).LotRptIsIgnore(inValue)
            Return retVal.Body.LotRptIsIgnoreResult
        End Function
    End Class
End Namespace
