'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace Rohm.ApcsWeb
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Rohm.ApcsWeb.ApcsWebServiceSoap")>  _
    Public Interface ApcsWebServiceSoap
        
        'CODEGEN: Generating message contract since element name mcNo from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LotRptIgnoreError", ReplyAction:="*")>  _
        Function LotRptIgnoreError(ByVal request As Rohm.ApcsWeb.LotRptIgnoreErrorRequest) As Rohm.ApcsWeb.LotRptIgnoreErrorResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LotRptIgnoreErrorRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LotRptIgnoreError", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Rohm.ApcsWeb.LotRptIgnoreErrorRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Rohm.ApcsWeb.LotRptIgnoreErrorRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class LotRptIgnoreErrorRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public mcNo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public errorCode As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal mcNo As String, ByVal errorCode As String)
            MyBase.New
            Me.mcNo = mcNo
            Me.errorCode = errorCode
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class LotRptIgnoreErrorResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="LotRptIgnoreErrorResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As Rohm.ApcsWeb.LotRptIgnoreErrorResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As Rohm.ApcsWeb.LotRptIgnoreErrorResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class LotRptIgnoreErrorResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public LotRptIgnoreErrorResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal LotRptIgnoreErrorResult As Boolean)
            MyBase.New
            Me.LotRptIgnoreErrorResult = LotRptIgnoreErrorResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface ApcsWebServiceSoapChannel
        Inherits Rohm.ApcsWeb.ApcsWebServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class ApcsWebServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of Rohm.ApcsWeb.ApcsWebServiceSoap)
        Implements Rohm.ApcsWeb.ApcsWebServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function Rohm_ApcsWeb_ApcsWebServiceSoap_LotRptIgnoreError(ByVal request As Rohm.ApcsWeb.LotRptIgnoreErrorRequest) As Rohm.ApcsWeb.LotRptIgnoreErrorResponse Implements Rohm.ApcsWeb.ApcsWebServiceSoap.LotRptIgnoreError
            Return MyBase.Channel.LotRptIgnoreError(request)
        End Function
        
        Public Function LotRptIgnoreError(ByVal mcNo As String, ByVal errorCode As String) As Boolean
            Dim inValue As Rohm.ApcsWeb.LotRptIgnoreErrorRequest = New Rohm.ApcsWeb.LotRptIgnoreErrorRequest
            inValue.Body = New Rohm.ApcsWeb.LotRptIgnoreErrorRequestBody
            inValue.Body.mcNo = mcNo
            inValue.Body.errorCode = errorCode
            Dim retVal As Rohm.ApcsWeb.LotRptIgnoreErrorResponse = CType(Me,Rohm.ApcsWeb.ApcsWebServiceSoap).LotRptIgnoreError(inValue)
            Return retVal.Body.LotRptIgnoreErrorResult
        End Function
    End Class
End Namespace
